export { default as inputs} from './inputs'
export { default as styles } from './styles'
export { default as assets } from './assets'
export { default as plugins } from './plugins'
export { default as settings } from './settings'
export { default as tecaptions } from './tecaptions'